export default {
  LOGIN: "Login",
  REGISTER: "Register",
  FORGOT_PASSWORD: "Forgot Password",
  SELECT_COUNTRY: "Select Country",
  LOGIN_SIGNUP: "Login SignUp",
  HavePurchase: "Have Purchase",
  CUSTUMIZE_SCREEN: "Custumize screen",
  HOMEPAGE: "Home Page",
  TOTALBALANCE: "Total Balance",
  TABBAR: "tab bar",
  VERIFY_ACCOUNT: "verify account",
  SIDE_DRAWER: "side drawer",
  PROFILE_SETTING: "profile Setting",
  HELP_AND_SUPPROT: "help and support",
  SECURTY: "security",
  ABOUT: "about",
  NOTIFICATIONS: "notifications",
  CHANGE_PASSWORD: "change password",
  BUY_COINS: "buy coins",
  REFER_FREIND: "refer friend",
  PAYMENT_SETTING: "payment setting",
  COIN_DETAIL: "coin detail",
  EDIT_NAME: "edit name",
  ORDER_REMINDER: "order Reminder",
  PURCHASED_CRYPTO: "purchsed crypto",

  HOME: "Home",
  HOME_TAB: "Home Tab",
  HOME_DRAWER: "Home Drawer",

  WALLET: "Wallet",
  WALLET_DRAWER: "Wallet Drawer",

  NOTIFICATIONS: "Notifications",
  NOTIFICATIONS_DRAWER: "Notifications Drawer",

  SETTINGS: "Settings",
  ACCOUNT_SETTINGS: "Account Settings",
  SETTINGS_NAVIGATOR: "Settings Navigator",

  SETTINGS_DETAIL: "Settings Detail",
  PROFILE: "My Profile",
};
